export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

export const LOG_IN_REQUEST = "LOG_IN_REQUEST";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAIL = "LOG_IN_FAIL";

export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAIL = "USER_FAIL";

export const MY_PROFILE_REQUEST = "MY_PROFILE_REQUEST";
export const MY_PROFILE_SUCCESS = "MY_PROFILE_SUCCESS";
export const MY_PROFILE_FAIL = "MY_PROFILE_FAIL";

export const CREATE_PROFILE_REQUEST = "CREATE_PROFILE_REQUEST";
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";
export const CREATE_PROFILE_FAIL = "CREATE_PROFILE_FAIL";

export const EDIT_PROFILE_REQUEST = "EDIT_PROFILE_REQUEST";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAIL = "EDIT_PROFILE_FAIL";

export const ADD_EXP_REQUEST = "ADD_EXP_REQUEST";
export const ADD_EXP_SUCCESS = "ADD_EXP_SUCCESS";
export const ADD_EXP_FAIL = "ADD_EXP_FAIL";

export const ADD_EDU_REQUEST = "ADD_EDU_REQUEST";
export const ADD_EDU_SUCCESS = "ADD_EDU_SUCCESS";
export const ADD_EDU_FAIL = "ADD_EDU_FAIL";

export const DELETE_EXP_REQUEST = "DELETE_EXP_REQUEST";
export const DELETE_EXP_SUCCESS = "DELETE_EXP_SUCCESS";
export const DELETE_EXP_FAIL = "DELETE_EXP_FAIL";

export const DELETE_EDU_REQUEST = "DELETE_EDU_REQUEST";
export const DELETE_EDU_SUCCESS = "DELETE_EDU_SUCCESS";
export const DELETE_EDU_FAIL = "DELETE_EDU_FAIL";

export const PROFILE_BY_ID_REQUEST = "PROFILE_BY_ID_REQUEST";
export const PROFILE_BY_ID_SUCCESS = "PROFILE_BY_ID_SUCCESS";
export const PROFILE_BY_ID_FAIL = "PROFILE_BY_ID_FAIL";

export const ALL_POSTS_REQUEST = "ALL_POSTS_REQUEST";
export const ALL_POSTS_SUCCESS = "ALL_POSTS_SUCCESS";
export const ALL_POSTS_FAIL = "ALL_POSTS_FAIL";

export const NEW_POST_REQUEST = "NEW_POST_REQUEST";
export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS";
export const NEW_POST_FAIL = "NEW_POST_FAIL";

//utility
export const RESET_STATE = "RESET_STATE";
export const TOGGLE = "TOGGLE";